# Generated by Django 5.0.6 on 2024-07-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detected_objects',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
